# Generated by Django 6.0.6 on 2026-06-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia_museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('anios_experiencia_guia', models.IntegerField()),
                ('idiomas_hablados', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=150)),
                ('anio_fundacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(max_length=200)),
                ('duracion_meses', models.IntegerField()),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tematica', models.CharField(max_length=200)),
                ('museo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposiciones', to='institucion.guia_museo')),
            ],
        ),
        migrations.AddField(
            model_name='guia_museo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='institucion.museo'),
        ),
    ]
